### ISSUE TITLE
Add Test: Checklist for workshopper owner than needs to be disabled

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/workshopper-adventure-test#29]
Have a checklist file in the repo that contains an entry for following parts.
The checklist is only for the writer and should only benefit to their task
- [ ] Are the sections solvable by just reading the specifications or is required information hidden in the "Hints"?
- [ ] Are the files created in the sections interesting for purposes outside of the nodeschool? Do they have wit and/or practical use?
- [ ] Did someone check-read the text?
- [ ] Does the tutorial explain the relevance of the topic? (Why should someone learn it?)
- [ ] Is there variance to the tests that makes sure that people don't trick the results?
- [ ] Are all the required/recommended modules added to the dependencies folder so people can use the workshopper offline?
- [ ] Is all the required documentation copied into a folder for offline use?
